const colorSchemas = [
  {
    primary: '#6527BE',
    secondary: '#45CFDD',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#6527BE',
    secondary: '#45CFDD',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#6527BE',
    secondary: '#9681EB',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#6527BE',
    secondary: '#9681EB',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#793FDF',
    secondary: '#7091F5',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#793FDF',
    secondary: '#7091F5',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#313866',
    secondary: '#504099',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#313866',
    secondary: '#504099',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#191D88',
    secondary: '#1450A3',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#191D88',
    secondary: '#1450A3',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#0C356A',
    secondary: '#279EFF',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#0C356A',
    secondary: '#279EFF',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'light-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#45CFDD',
    secondary: '#6527BE',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#45CFDD',
    secondary: '#6527BE',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#EF9595',
    secondary: '#FFBB5C',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#EF9595',
    secondary: '#FFBB5C',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#DFD7BF',
    secondary: '#3F2305',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#DFD7BF',
    secondary: '#3F2305',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#A4D0A4',
    secondary: '#A4907C',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#A4D0A4',
    secondary: '#A4907C',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#A4D0A4',
    secondary: '#617A55',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#A4D0A4',
    secondary: '#617A55',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'dark',
  },
  {
    primary: '#A4907C',
    secondary: '#617A55',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'light',
  },
  {
    primary: '#A4907C',
    secondary: '#617A55',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: 'dark-content',
    datePickerThemeVaiant: 'dark',
  },
].map((schema, index) => ({
  ...schema,
  id: index,
}));

export default colorSchemas;
