export enum StatusBarStyle {
  LIGHT = 'light-content',
  DARK = 'dark-content',
}

export enum DatePickerThemeVaiant {
  LIGHT = 'light',
  DARK = 'dark',
}

export type ThemeColors = {
  id: number;
  primary: string;
  secondary: string;
  background: string;
  surface: string;
  onPrimary: string;
  onSecondary: string;
  onSurface: string;
  onBackground: string;
  statusBarStyle: StatusBarStyle;
  datePickerThemeVaiant: DatePickerThemeVaiant;
};
const colorSchemas: ThemeColors[] = [
  {
    primary: '#6527BE',
    secondary: '#45CFDD',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#6527BE',
    secondary: '#45CFDD',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#6527BE',
    secondary: '#9681EB',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#6527BE',
    secondary: '#9681EB',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#793FDF',
    secondary: '#7091F5',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#793FDF',
    secondary: '#7091F5',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#313866',
    secondary: '#504099',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#313866',
    secondary: '#504099',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#191D88',
    secondary: '#1450A3',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#191D88',
    secondary: '#1450A3',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#0C356A',
    secondary: '#279EFF',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#0C356A',
    secondary: '#279EFF',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.LIGHT,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#45CFDD',
    secondary: '#6527BE',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#45CFDD',
    secondary: '#6527BE',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#EF9595',
    secondary: '#FFBB5C',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#EF9595',
    secondary: '#FFBB5C',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#DFD7BF',
    secondary: '#3F2305',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#DFD7BF',
    secondary: '#3F2305',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#A4D0A4',
    secondary: '#A4907C',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#A4D0A4',
    secondary: '#A4907C',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#A4D0A4',
    secondary: '#617A55',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#A4D0A4',
    secondary: '#617A55',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
  {
    primary: '#A4907C',
    secondary: '#617A55',
    surface: '#FFFFFF',
    background: '#DDDDDD',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#000000',
    onBackground: '#000000',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.LIGHT,
  },
  {
    primary: '#A4907C',
    secondary: '#617A55',
    surface: '#212121',
    background: '#121212',
    onPrimary: '#000000',
    onSecondary: '#FFFFFF',
    onSurface: '#FFFFFF',
    onBackground: '#FFFFFF',
    statusBarStyle: StatusBarStyle.DARK,
    datePickerThemeVaiant: DatePickerThemeVaiant.DARK,
  },
].map((schema, index) => ({
  ...schema,
  id: index,
}));

export default colorSchemas;
